id: AE931D985
title: Toh_194-The_Sutra_of_Jayamati-v1
type: translation
pechas:
- IB14D2F2D
- I30301754
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-05-03T06:51:41.225Z'
  creationid: dolma
  eft-text-id: UT22084-061-014
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_194-The_Sutra_of_Jayamati-v1
alignment_to_base:
  IB14D2F2D/E523: 88D9
  I30301754/0DEA: 88D9
